Making script a bit smarter for creation of server-type list and service/containers checks

diff --git a/insanity-service-check b/insanity-service-check
--- a/insanity-service-check
+++ b/insanity-service-check
@@ -1,16 +1,22 @@
 #!/usr/bin/env bash
 
-# VARS
+# VARS PART 1
 HOSTSDIR='hosts'
 MODE=$3
 CONFDIR='conf'
 SERVER_LIST=$1
 ESC="\e["
 LOGDIR='./log'
+LOGFILE="${MODE}-${SERVER_LIST}-${DATE}.log"
+GREEN="${ESC}32m"
+RED="${ESC}31m"
+YELLOW="${ESC}33m"
+BOLD="${ESC}1m"
+NORMAL="${ESC}0m"
 
 # Test if SERVER_LIST exists
 if [[ ! -e $HOSTSDIR/$SERVER_LIST ]]; then
-  printf "${RED}FAIL: Can't find server list, please check it.${NORMAL}" | tee -a $LOGDIR/$LOGFILE; exit 1
+  printf "${RED}${BOLD}FAIL${NORMAL}: Can't find server list, please check it.\n" | tee -a $LOGDIR/$LOGFILE; exit 1
 fi
 
 # Create log direrctory
@@ -21,10 +27,10 @@ fi
 # Usage function
 usage() {
   echo -e "${BOLD}USAGE${NORMAL}:
-  ${YELLOW}$0 server-list user mode (service|marker) [sudo]${ESC}0m\n${BOLD}Examples${NORMAL}:
-  ${YELLOW}$0 devjboss root marker
-  $0 qajboss devops service sudo
-  $0 prodjboss nicon marker sudo${ESC}0m"; exit 1
+  ${YELLOW}$0 server-list user mode (service|marker) [sudo]${NORMAL}\n${BOLD}Examples${NORMAL}:
+  ${YELLOW}$0 risdevinteractive root marker
+  $0 risqainteractive1 ricie service sudo
+  $0 risbdcinteractive2 pkowalczyk marker sudo${NORMAL}"; exit 1
 }
 
 # Test nummber of parameters
@@ -32,34 +38,23 @@ if [[ ( $# != 3 && $# != 4 ) ]]; then
   usage
 fi
 
+# VARS PART 2
 PASS=$(cat ${CONFDIR}/.passwd)
 USER=$2
 SUDO=$4
 DATE=`date +%m%d%y_%H%M`
 TMPDIR='./tmp'
-LOGFILE="${MODE}-${SERVER_LIST}-${DATE}.log"
-PNWEB=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pnweb | awk {'print $1'})
-PNAPP=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pnapp | awk {'print $1'})
-PNBOWEB=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pnboweb | awk {'print $1'})
-PNBOAPP=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pnboapp | awk {'print $1'})
-PNBROKER=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pnbroker | awk {'print $1'})
-PNCRM=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pncrm | awk {'print $1'})
-PNGAME=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pngame | awk {'print $1'})
-PN2DB=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pn2db | awk {'print $1'})
-PN2PAM=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pn2pam | awk {'print $1'})
-PN2CONNECT=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pn2connect | awk {'print $1'})
-PN2BROKER=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pn2broker | awk {'print $1'})
-PN2BOWEB=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pn2boweb | awk {'print $1'})
-PN2BOAPP=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i pn2boapp | awk {'print $1'})
 DISABLED_LIST="${CONFDIR}/disabled-list"
 FAIL=0
 WARN=0
-GREEN="${ESC}32m"
-RED="${ESC}31m"
-YELLOW="${ESC}33m"
-BOLD="${ESC}1m"
-NORMAL="${ESC}0m"
-RANDOM_SERVER=`head -$((${RANDOM} % \`wc -l < ${HOSTSDIR}/${SERVER_LIST}\` + 1)) ${HOSTSDIR}/${SERVER_LIST} | tail -1`
+RANDOM_SERVER=`head -$((${RANDOM} % \`wc -l < ${HOSTSDIR}/${SERVER_LIST}\` + 1)) ${HOSTSDIR}/${SERVER_LIST} | awk {'print $1'} | tail -1`
+SERVERS=()
+for SERVER in PNWEB PNAPP PNBOWEB PNBOAPP PNBROKER PNCRM PNGAME PN2DB PN2PAM PN2CONNECT PN2BROKER PN2BOWEB PN2BOAPP; do
+  eval ${SERVER}=$(cat ${HOSTSDIR}/${SERVER_LIST} | grep -i $SERVER | awk {'print $1'})
+  if [ ! -z ${!SERVER} ]; then
+    SERVERS+=(${SERVER})
+  fi
+done
 
 # SSH test
 sshtest() {
@@ -86,68 +81,72 @@ mkdir $TMPDIR
 
 # Service Function
 service() {
-  for SERVER in PNWEB PNAPP PNBOWEB PNBOAPP PNBROKER PNCRM PNGAME PN2DB PN2PAM PN2CONNECT PN2BROKER PN2BOWEB PN2BOAPP; do
-    printf "\n${ESC};4m${BOLD}Checking services on ${!SERVER}${ESC}0m\n"
-    for SERVICE in `cat ${CONFDIR}/${SERVER}-service-list`; do
-      COMMAND=`sshpass -p ${PASS} ssh -q -t -o StrictHostKeyChecking=no $USER@${!SERVER} "${SUDO_PREFIX} /bin/sh -c 'systemctl status ${SERVICE} > /dev/null 2>&1'"`; RC=$?
-      if [[ $RC -ne 0 ]]; then
-        if egrep -q "^${SERVICE}$" ${DISABLED_LIST}; then
-          printf "${YELLOW}${BOLD}WARN${NORMAL}: ${BOLD}Disabled${NORMAL} service check ${SERVICE} return code: ${TAB}${RC}${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; WARN=$((WARN+1))
+  for SERVER in ${SERVERS[@]}; do
+    if [[ -e ${CONFDIR}/${SERVER}-service-list ]]; then
+      printf "\n${ESC}4m${BOLD}Checking services on ${!SERVER}${NORMAL}${ESC}24m\n" | tee -a $LOGDIR/$LOGFILE
+      for SERVICE in `cat ${CONFDIR}/${SERVER}-service-list`; do
+        COMMAND=`sshpass -p ${PASS} ssh -q -t -o StrictHostKeyChecking=no $USER@${!SERVER} "${SUDO_PREFIX} /bin/sh -c 'systemctl status ${SERVICE} > /dev/null 2>&1'"`; RC=$?
+        if [[ $RC -ne 0 ]]; then
+          if egrep -q "^${SERVICE}$" ${DISABLED_LIST}; then
+            printf "${YELLOW}${BOLD}WARN${NORMAL}: ${BOLD}Disabled${NORMAL} service check ${SERVICE} return code: ${TAB}${RC}${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; WARN=$((WARN+1))
+          else
+            printf "${RED}${BOLD}FAIL${NORMAL}: Service check ${SERVICE} return code: ${TAB}${RC}${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; FAIL=$((FAIL+1))
+          fi
         else
-          printf "${RED}${BOLD}FAIL${NORMAL}: Service check ${SERVICE} return code: ${TAB}${RC}${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; FAIL=$((FAIL+1))
+          if egrep -q "^${SERVICE}$" ${DISABLED_LIST}; then
+            printf "${RED}${BOLD}FAIL${NORMAL}: ${BOLD}disabled${NORMAL} Service check ${SERVICE} return code: ${TAB}${RC}${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; FAIL=$((FAIL+1))
+          else
+            printf "${GREEN}${BOLD}OKAY${NORMAL}: Service check ${SERVICE} return code: ${TAB}${RC}${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE
+          fi
         fi
-      else
-        if egrep -q "^${SERVICE}$" ${DISABLED_LIST}; then
-          printf "${RED}${BOLD}FAIL${NORMAL}: ${BOLD}disabled${NORMAL} Service check ${SERVICE} return code: ${TAB}${RC}${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; FAIL=$((FAIL+1))
-        else
-          printf "${GREEN}${BOLD}OKAY${NORMAL}: Service check ${SERVICE} return code: ${TAB}${RC}${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE
-        fi
-      fi
-    done
+      done
+    fi
   done
 }
 
 # Marker function
 marker() {
-  for SERVER in PDAPP PDBOAPP PDCRM PDGAME CMDPAM CMDCONNECT CMDBOAPP; do
-    for CONTAINER in `cat ${CONFDIR}/${SERVER}-container-list`; do
-      printf "\n${ESC}4m${BOLD}Searching for markers on ${!SERVER} in /usr/share/jbossas/${CONTAINER}${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE
-      EXIST_CHECK=`sshpass -p ${PASS} ssh -q -t -o StrictHostKeyChecking=no $USER@${!SERVER} "${SUDO_PREFIX} /bin/sh -c \"[[ -e /usr/share/jbossas/${CONTAINER}/deployments ]]\""`; RC=$?
-      if [[ $RC -eq 0 ]]; then
-        sshpass -p ${PASS} ssh -q -t -o StrictHostKeyChecking=no $USER@${!SERVER} "${SUDO_PREFIX} /bin/sh -c \"find /usr/share/jbossas/${CONTAINER}/deployments -name '*.deployed'\"" > ${TMPDIR}/${SERVER}-${CONTAINER}.deployed
-        sshpass -p ${PASS} ssh -q -t -o StrictHostKeyChecking=no $USER@${!SERVER} "${SUDO_PREFIX} /bin/sh -c \"find /usr/share/jbossas/${CONTAINER}/deployments -name '*.failed'\"" > ${TMPDIR}/${SERVER}-${CONTAINER}.failed
-      	DEPLOYED=`grep -v sudo $TMPDIR/${SERVER}-${CONTAINER}.deployed | wc -l`
-      	FAILED=`grep -v sudo $TMPDIR/${SERVER}-${CONTAINER}.failed | wc -l`
-        if [[ $DEPLOYED -gt 1 ]]; then
-          if egrep -q "^${CONTAINER}$" ${DISABLED_LIST}; then
-            echo -e "${RED}${BOLD}FAIL${NORMAL}: Found *.deployed files, even though container ${CONTAINER} is ${BOLD}disabled${NORMAL}!\n\n
-            ${BOLD}Deployed:${NORMAL}\n`cat $TMPDIR/${SERVER}-${CONTAINER}.deployed | grep -v sudo`${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE
-            FAIL=$((FAIL+1))
+  for SERVER in ${SERVERS[@]}; do
+    if [[ -e ${CONFDIR}/${SERVER}-container-list ]]; then
+      for CONTAINER in `cat ${CONFDIR}/${SERVER}-container-list`; do
+        printf "\n${ESC}4m${BOLD}Searching for markers on ${!SERVER} in /usr/share/jbossas/${CONTAINER}${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE
+        EXIST_CHECK=`sshpass -p ${PASS} ssh -q -t -o StrictHostKeyChecking=no $USER@${!SERVER} "${SUDO_PREFIX} /bin/sh -c \"[[ -e /usr/share/jbossas/${CONTAINER}/deployments ]]\""`; RC=$?
+        if [[ $RC -eq 0 ]]; then
+          sshpass -p ${PASS} ssh -q -t -o StrictHostKeyChecking=no $USER@${!SERVER} "${SUDO_PREFIX} /bin/sh -c \"find /usr/share/jbossas/${CONTAINER}/deployments -name '*.deployed'\"" > ${TMPDIR}/${SERVER}-${CONTAINER}.deployed
+          sshpass -p ${PASS} ssh -q -t -o StrictHostKeyChecking=no $USER@${!SERVER} "${SUDO_PREFIX} /bin/sh -c \"find /usr/share/jbossas/${CONTAINER}/deployments -name '*.failed'\"" > ${TMPDIR}/${SERVER}-${CONTAINER}.failed
+          DEPLOYED=`grep -v sudo $TMPDIR/${SERVER}-${CONTAINER}.deployed | wc -l`
+          FAILED=`grep -v sudo $TMPDIR/${SERVER}-${CONTAINER}.failed | wc -l`
+          if [[ $DEPLOYED -gt 1 ]]; then
+            if egrep -q "^${CONTAINER}$" ${DISABLED_LIST}; then
+              echo -e "${RED}${BOLD}FAIL${NORMAL}: Found *.deployed files, even though container ${CONTAINER} is ${BOLD}disabled${NORMAL}!\n\n
+              ${BOLD}Deployed:${NORMAL}\n`cat $TMPDIR/${SERVER}-${CONTAINER}.deployed | grep -v sudo`${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE
+              FAIL=$((FAIL+1))
+            else
+              printf "${GREEN}${BOLD}OKAY${NORMAL}: Found *.deployed files in ${CONTAINER} container.\n\n${BOLD}Deployed:${NORMAL}\n`cat $TMPDIR/${SERVER}-${CONTAINER}.deployed | grep -v sudo`${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE
+            fi
           else
-            printf "${GREEN}${BOLD}OKAY${NORMAL}: Found *.deployed files in ${CONTAINER} container.\n\n${BOLD}Deployed:${NORMAL}\n`cat $TMPDIR/${SERVER}-${CONTAINER}.deployed | grep -v sudo`${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE
+            if egrep -q "^${CONTAINER}$" ${DISABLED_LIST}; then
+              printf "${YELLOW}${BOLD}WARN${NORMAL}: No *.deployed files found in ${BOLD}disabled${NORMAL} container ${CONTAINER}.${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; WARN=$((WARN+1))
+            else
+              printf "${RED}${BOLD}FAIL${NORMAL}: No *.deployed files found in container ${CONTAINER}!${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; FAIL=$((FAIL+1))
+            fi
+          fi
+          if [[ $FAILED -gt 1 ]]; then
+            if egrep -q "^${CONTAINER}$" ${DISABLED_LIST}; then
+              echo -e "${RED}${BOLD}FAIL${NORMAL}: Found *.failed files, even though container ${CONTAINER} is ${BOLD}disabled${NORMAL}!\n\n${BOLD}Failed:${NORMAL}\n`cat $TMPDIR/${SERVER}-${CONTAINER}.failed | grep -v sudo`${NORMAL}" | tee -a $LOGDIR/$LOGFILE; FAIL=$((FAIL+1))
+            else
+              printf "${RED}\n${BOLD}Failed:${NORMAL}\n`cat $TMPDIR/${SERVER}-${CONTAINER}.failed | grep -v sudo`${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; FAIL=$((FAIL+1))
+            fi
           fi
         else
           if egrep -q "^${CONTAINER}$" ${DISABLED_LIST}; then
-            printf "${YELLOW}${BOLD}WARN${NORMAL}: No *.deployed files found in ${BOLD}disabled${NORMAL} container ${CONTAINER}.${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; WARN=$((WARN+1))
+            printf "${YELLOW}${BOLD}WARN${NORMAL}: Directory /usr/share/jbossas/${CONTAINER} (${BOLD}disabled${NORMAL}) doesn't exists.${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; WARN=$((WARN+1))
           else
-            printf "${RED}${BOLD}FAIL${NORMAL}: No *.deployed files found in container ${CONTAINER}!${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; FAIL=$((FAIL+1))
+            printf "${RED}FAIL: Directory /usr/share/jbossas/${CONTAINER} doesn't exists.${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; FAIL=$((FAIL+1))
           fi
         fi
-        if [[ $FAILED -gt 1 ]]; then
-          if egrep -q "^${CONTAINER}$" ${DISABLED_LIST}; then
-            echo -e "${RED}${BOLD}FAIL${NORMAL}: Found *.failed files, even though container ${CONTAINER} is ${BOLD}disabled${NORMAL}!\n\n${BOLD}Failed:${NORMAL}\n`cat $TMPDIR/${SERVER}-${CONTAINER}.failed | grep -v sudo`${NORMAL}" | tee -a $LOGDIR/$LOGFILE; FAIL=$((FAIL+1))
-          else
-            printf "${RED}\n${BOLD}Failed:${NORMAL}\n`cat $TMPDIR/${SERVER}-${CONTAINER}.failed | grep -v sudo`${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; FAIL=$((FAIL+1))
-          fi
-        fi
-      else
-        if egrep -q "^${CONTAINER}$" ${DISABLED_LIST}; then
-          printf "${YELLOW}${BOLD}WARN${NORMAL}: Directory /usr/share/jbossas/${CONTAINER} (${BOLD}disabled${NORMAL}) doesn't exists.${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; WARN=$((WARN+1))
-        else
-          printf "${RED}FAIL: Directory /usr/share/jbossas/${CONTAINER} doesn't exists.${NORMAL}\n" | tee -a $LOGDIR/$LOGFILE; FAIL=$((FAIL+1))
-        fi
-      fi
-    done
+      done
+    fi
   done
   rm -rf $TMPDIR
 }
